### ISSUE TITLE
CTRL+C Terminal corruption

### ISSUE THREAD

**Issue by TerminalMan** [gRastello/nao#3]
When running the program via: go run nao.go review "deck" 

And afterwards killing the program via "CTRL+C" the terminal ends up being corrupted. In my case I can type but the characters do not show up in the terminal. Running 'reset' fixes the session.

**Comment by gRastello** [comment]
This issue is probably due to Nao calling `stty` in the `getKey` function; I'm actually thinking about removing this in favor of a more traditional character reading technique (namely one that requires you to press Enter) and also because I don't really like relying on an external process like that. I'll fix that soon.

**Comment by gRastello** [comment]
I've removed the dependence from `stty` and pushed changes to the `develop` branch so the problem should be gone for good with the next version.
